<a href="https://colab.research.google.com/github/Mani-gmk/Numpy_in-Python/blob/main/19_DA_Numpy_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DA_Numpy_Python

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
np.__version__

'2.1.3'

### Array Initialization - Single Dimension

In [ ]:
import numpy as np
a = np.array([7,9,9,2])
print(a)

[7 9 9 2]


### Array Initialization - Multi Dimension

In [ ]:
import numpy as np
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]


###Generating Array


In [ ]:
c = np.arange(10) #range of values in array
d = np.linspace(0,10,5) #set of values by Interval [start,end,no.ofvaluesEqualInterval]
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


### Array Properties

In [ ]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b.ndim) #Dimension of Array
print(a.itemsize) #Byte Size of each Element
print(a.dtype) #Datatype of array
print(b.size*b.itemsize) #memory occupied - space occupied by 1 element * length of numpy array
print(a.size) #number of elements in array
print(b.shape) #shape of array (rows and columns)

2
8
int64
64
4
(2, 4)


### Array Reshape

In [ ]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b = b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


### Array Slicing

In [ ]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)
print(b[0,2]) #Slicing the Element from certain row and certain column b[rowIndex,ColumnIndex]
print(b[0:,2]) #Slicing Element from all rows and certain column

[[ 7  9  9  2]
 [16 11  9  6]]
9
[9 9]


### Array Value Operation

In [ ]:
e = np.array([7,9,9,2,16,11,96])
print(e.min()) #Minimum value in array
print(e.max()) #Maximum value in array
print(e.sum()) #Sum of array

2
96
150


###Array Arithmetic Operation


In [ ]:
a = np.array([7,9,9,2])
c = np.array([1,9,9,6])
print(a+c)
print(a-c)
print(a*c)
print(a/c)

[ 8 18 18  8]
[ 6  0  0 -4]
[ 7 81 81 12]
[7.         1.         1.         0.33333333]


In [ ]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0)) #Each element of 1st dim array with same index with another dim element
print(b.sum(axis=1)) #sum of all element is 1st dim & sum of all element is 2nd dim
print(np.sqrt(a)) #Squareroot of array elements
print(np.std(a)) #Standard Deviation of array
print(np.exp(a)) #Exponential of array
print(np.log(a)) #Natural Log - ln
print(np.log10(a)) #Log base 10

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [ ]:
b = np.array([(7,9,9,2),(16,11,9,6)])
f = np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f))) #Vertical Stack
print(np.hstack((b,f))) #Horizontal Stack
print(b.ravel()) #Merging as single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]
